include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'

linter:
  rules:
    # Additional recommended rules
    always_declare_return_types: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    use_full_hex_values_for_flutter_colors: true

    # Safe and clean code practices
    avoid_returning_null_for_future: true
    avoid_void_async: true
    parameter_assignments: false
