name: Rollback Flutter Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to rollback to (e.g., 1.2.3)'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # pour accéder aux tags

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Checkout version ${{ github.event.inputs.version }}
        run: git checkout tags/${{ github.event.inputs.version }}

      - name: Reset branch main to this tag
        run: |
          git checkout -B main
          git push origin main --force

      - name: Create rollback tag
        run: |
          ROLLBACK_TAG="${{ github.event.inputs.version }}-rollback"
          git tag -a "$ROLLBACK_TAG" -m "Rollback to version ${{ github.event.inputs.version }}"
          git push origin "$ROLLBACK_TAG"

      - name: Create GitHub Release
        run: |
          gh release create "$ROLLBACK_TAG" --title "Rollback $ROLLBACK_TAG" --notes "Rollback to version ${{ github.event.inputs.version }}"
