name: Deploy Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install GitHub CLI (portable)
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.49.0/gh_2.49.0_linux_amd64.tar.gz | tar xz
          sudo mv gh_2.49.0_linux_amd64/bin/gh /usr/local/bin/gh

      - name: Make release script executable
        run: chmod +x ./scripts/release.sh

      - name: Run release
        shell: bash
        run: ./scripts/release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge_release_to_main:
    name: Merge release into main
    needs: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge release → main
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git merge origin/release -X theirs --no-edit
          git push origin main
